In [2]:
import pandas as pd
import os

In [3]:
dfs = [] # lista vazia para armazenar os dataframes

# percorre todas as pastas dentro do caminho especificado
for folder in os.listdir(r'D:\repositorios git\HVEX\dados\raw_data'):
    # percorre todos os arquivos dentro da pasta atual
    for file in os.listdir(r'D:\repositorios git\HVEX\dados\raw_data\{}'.format(folder)):

        # verifica se o nome do arquivo contém 'DataSheet'
        if 'DataSheet' in file:
            # lê o arquivo csv especificado e armazena o dataframe na lista dfs
            dfs.append(pd.read_csv(r'D:\repositorios git\HVEX\dados\raw_data\{}\{}'.format(folder, file),
                                  skiprows=[0,1], sep=';', encoding='UTF-8'))
            # verifica se o dataframe contém apenas uma coluna
            if dfs[-1].shape[1] == 1:
                # se o dataframe contiver apenas uma coluna, lê novamente o arquivo csv, alterando o separador para vírgula
                dfs[-1] = pd.read_csv(r'D:\repositorios git\HVEX\dados\raw_data\{}\{}'.format(folder, file),
                                  skiprows=[0,1], sep=',', encoding='UTF-8')

In [4]:
def padrao(data):
    data = data.split('-')
    ano = data[0]
    dia = data[-1]
    data = '{}/{}/{}'.format(dia, data[1], ano)

    return data

# Padronizandno as datas do dataframe
dfs[-1]['Date'] = dfs[-1]['Date'].apply(lambda x: padrao(x))

In [5]:
# O ultimo ds contem uma coluna a mais por causa da substituição que fiz manualmente
dfs[-1].drop('Unnamed: 73', axis='columns', inplace=True) # Removendo coluna inutil

In [6]:
datasheet = pd.concat(dfs) #concatenando todos os dataframes, vai ser melhor para a visualização

In [12]:
# Verificando a existência de nulos no df
print([coluna for coluna in datasheet.isna().sum()])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [7]:
datasheet.shape

(10080, 73)

In [8]:
# Contar o número de valores nulos em cada coluna
nulos_por_coluna = datasheet.isnull().sum()
[print(values) for values in nulos_por_coluna if values > 0]

[]

In [9]:
datasheet.describe()

,UA,UB,UC,UAvg,UN,UTHDA,UTHDB,UTHDC,UTHDAvg,IA,...,PDmIA,PDmIB,PDmIC,PDmIAVG,DmP,PDmP,DmQ,PDmQ,DmS,PDmS
count,10080.000000,10080.000000,10080.000000,10080.000000,10080.0,10080.000000,10080.000000,10080.000000,10080.000000,10080.000000,...,10080.000000,10080.000000,10080.000000,10080.000000,10080.000000,10080.0,10080.000000,10080.000000,10080.000000,10080.000000
mean,125.832443,126.704181,123.366787,125.301145,0.0,2.306172,2.371813,2.353044,2.343678,115.158444,...,227.098815,224.598766,243.311764,230.762126,-41187.893510,0.0,18678.477243,41801.757497,45522.178868,85271.789035
std,16.556721,16.622652,16.199787,16.440907,0.0,0.506675,0.444520,0.469185,0.446814,46.913059,...,44.598743,38.796647,49.622248,44.891680,15362.548904,0.0,8714.268801,8571.092851,17463.740451,16215.164011
min,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,97.740000,115.410000,103.520000,104.240000,-79595.480000,0.0,-25.740000,16111.480000,0.000000,39567.020000
25%,126.920000,127.690000,124.280000,126.380000,0.0,2.102000,2.183000,2.112000,2.157000,81.010000,...,242.960000,237.670000,259.570000,246.730000,-51372.322500,0.0,11650.685000,44847.040000,31285.120000,91039.470000
50%,128.070000,128.880000,125.440000,127.500000,0.0,2.313000,2.391000,2.361000,2.358500,117.995000,...,242.960000,237.670000,259.570000,246.730000,-41871.535000,0.0,19574.540000,44847.040000,46618.895000,91039.470000
75%,129.220000,130.010000,126.600000,128.590000,0.0,2.545000,2.606000,2.643000,2.587000,147.730000,...,242.960000,239.850000,263.710000,246.730000,-29025.717500,0.0,24369.185000,44847.040000,57116.892500,91039.470000
max,140.800000,140.960000,133.280000,138.350000,0.0,23.581000,12.831000,7.118000,13.744000,350.450000,...,242.960000,239.850000,263.710000,246.730000,0.000000,0.0,44847.040000,44847.040000,91039.470000,91039.470000

In [10]:
# Criando uma coluna temporal mais detalhada
datasheet['Datetime'] = datasheet['Date'] + ' ' + datasheet['Time']

Pelo visto os valores de datasheet estão em conforme. Então podemos salvar esse dataset agora com todos os dias concatenados.

In [11]:
datasheet.to_csv(r'D:\repositorios git\HVEX\dados\DataSheet_3421198001_3P4W.csv',
                 encoding='UTF-8', sep=';', index=False)